---
title: "Final Project"
author: "Ray Lee"
date: "3/14/2021"
output: word_document
---

```{r mlbench}
library(mlbench)
library(e1071)
library(klaR)
library(nnet)
library(neuralnet)
library(MASS)
library(rpart)
library(randomForest)
library(caret)
library(stringr)
```

#Upload Breast Cancer Data Set

```{r}
data(BreastCancer)
BreastCancer
```

#Remove nulls

```{r}
BreastCancer <- na.omit(BreastCancer)
BreastCancer$Id <- NULL
for (i in 1:ncol(BreastCancer)) {
  BreastCancer[is.na(BreastCancer[,i]), i] <- floor(mean(as.numeric(BreastCancer[,i]), na.rm = TRUE))
}
BreastCancer$Malignant_1 <- ifelse(BreastCancer$Class == "malignant",1,0)  #Set our label to binary for our numerical data frame
BreastCancer.num <- as.data.frame(apply(BreastCancer[,2:11],2,as.numeric))
BreastCancer.num <- cbind(BreastCancer.num[10],BreastCancer.num[1:9]) # Reorder our numerical data frame so that our label is first
BreastCancer <- BreastCancer[,1:10] #Removes our numerical label from our factored data frame 
BreastCancer
```

Summary and Strcutre

```{r}
str(BreastCancer)
summary(BreastCancer)
```

#Change Variables to Integers

```{r}
BreastCancer$Cl.thickness <- as.numeric(BreastCancer$Cl.thickness)
BreastCancer$Cell.size <- as.numeric(BreastCancer$Cell.shape)
BreastCancer$Cell.shape <- as.numeric(BreastCancer$Cell.shape)
BreastCancer$Marg.adhesion <- as.numeric(BreastCancer$Marg.adhesion)
BreastCancer$Epith.c.size <- as.numeric(BreastCancer$Epith.c.size)
BreastCancer$Bl.cromatin <- as.numeric(BreastCancer$Bl.cromatin)
BreastCancer$Normal.nucleoli <- as.numeric(BreastCancer$Normal.nucleoli)
BreastCancer$Mitoses <- as.numeric(BreastCancer$Mitoses)
BreastCancer$Bare.nuclei <- as.numeric(BreastCancer$Bare.nuclei)
BreastCancer
```

#Split and Partition

```{r}
train.index <- sample(c(1:dim(BreastCancer)[1]), dim(BreastCancer)[1]*.6) # Sets our training data to 60% of our data
train.df <- BreastCancer[train.index, ]
valid.df <- BreastCancer[-train.index, ]
head(train.df)
head(valid.df)
```

#SVM

```{r}
accuracy.df <- data.frame(Model = seq(1, 8,1), Train_Accuracy_score = rep(0,8) ,Valid_Accuracy_score = rep(0,8))
svm <- svm(Class~., train.df)
svm.pred <- predict(svm, train.df)
accuracy.df[1,2] <- confusionMatrix(as.factor(svm.pred), as.factor(train.df$Class))$overall[1]
svm.v.pred <- predict(svm, valid.df)
accuracy.df[1,3] <- confusionMatrix(as.factor(svm.v.pred), as.factor(valid.df$Class))$overall[1]
```

#Naive Bayes

```{r}
nvb <- NaiveBayes(Class ~., train.df)
nvb.pred <- predict(nvb, train.df)
accuracy.df[2,2] <- confusionMatrix(as.factor(nvb.pred$class), as.factor(train.df$Class))$overall[1]
nvb.v.pred <- predict(nvb, valid.df)
accuracy.df[2,3] <- confusionMatrix(as.factor(nvb.v.pred$class), as.factor(valid.df$Class))$overall[1]
```

#Neural Net Prep

```{r}
train.num.df <- BreastCancer.num[train.index, ]
valid.num.df <- BreastCancer.num[-train.index, ]
norm_values <- preProcess(train.num.df[,2:10])
train.norm.df <- predict(norm_values, train.num.df)
valid.norm.df <- predict(norm_values, valid.num.df)
```

# Neural Net

```{r}
mynnet <- nnet(Class ~ ., BreastCancer, size=1)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
table(mynnet.pred,BreastCancer$Class)
```

# Decision Trees

```{r}
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree)
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)
```

# Leave-1-Out Cross Validation

```{r}
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```

#Regularised Discriminant Analysis

```{r}
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Class)
```

#Random Forests

```{r}
myrf <- randomForest(Class ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Class)
```

